- name: Install Python and Pip
  hosts: webserver
  gather_facts: no
  tasks:
    - name: Install python3 and pip3
      raw: sudo apt-get update && sudo apt-get install -y python3 python3-pip

- hosts: webserver
  become: yes           # run tasks with sudo
  roles:
    - docker
    - nginx
    - app
