- name: Install Python and Pip
  hosts: webserver
  gather_facts: no
  become: yes
  tasks:
    - name: Install python3 and pip3
      raw: sudo apt-get update && sudo apt-get install -y python3 python3-pip

    - name: Install six module
      pip:
        name: six
        executable: pip3

- hosts: webserver
  become: yes
  roles:
    - docker
    - nginx
    - app
