name: Deploy Yii2 App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest ./yii2-app
        docker push ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest

    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd DevOps-PHP-yii2-deployment
          git pull origin main
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/yii2-app:latest
          sudo docker stack deploy --compose-file docker-compose.yml mystack
